/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Wysiwyg = {
  _type: "wysiwyg";
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type VideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "video-asset";
};

export type Video = {
  _type: "video";
  asset?: VideoAssetReference;
  caption?: string;
  autoplay?: boolean;
  loop?: boolean;
  controls?: boolean;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type PageSettings = {
  _type: "page-settings";
  theme?: "light" | "dark";
  showFooter?: boolean;
  footerPage?: HomeReference;
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  page?: HomeReference;
  url?: string;
};

export type VideoAsset = {
  _id: string;
  _type: "video-asset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  altText?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  storyboard?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  storyboardColumns?: number;
  storyboardRows?: number;
  tags?: Array<string>;
  storageKey?: string;
  filename?: string;
  contentType?: string;
  size?: number;
  duration?: number;
  width?: number;
  height?: number;
  aspectRatio?: number;
  uploadedAt?: string;
  uploadedBy?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  showPreloader?: boolean;
  nav?: Array<
    {
      _key: string;
    } & Link
  >;
  siteIdentity?: {
    entityType?: "organization" | "person";
    name?: string;
    alternateName?: string;
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    jobTitle?: string;
    email?: string;
    sameAs?: Array<string>;
  };
  footer?: {
    heading?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    socials?: Array<
      {
        _key: string;
      } & Link
    >;
    copyright?: string;
  };
  fallbackSEO?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
  };
  aiContent?: {
    summary?: string;
    sections?: Array<{
      title?: string;
      items?: Array<string>;
      _type: "ai-section";
      _key: string;
    }>;
  };
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: Array<
    | ({
        _key: string;
      } & Video)
    | ({
        _key: string;
      } & Wysiwyg)
  >;
  seo?: Seo;
  settings?: PageSettings;
};

export type MediaFolderReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "media.folder";
};

export type MediaFolder = {
  _id: string;
  _type: "media.folder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  parent?: MediaFolderReference;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Wysiwyg
  | VideoAssetReference
  | Video
  | Seo
  | HomeReference
  | PageSettings
  | Link
  | VideoAsset
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | Home
  | MediaFolderReference
  | MediaFolder
  | MediaTag
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: homeQuery
// Query: *[_type == "home"][0]{  _updatedAt,  content[]{  ...,  _type == "video" => {    asset-> {  "id": _id,  title,  altText,  storageKey,  duration,  width,  height,  aspectRatio,  "poster": thumbnail.asset->url,  "posterLqip": thumbnail.asset->metadata.lqip}  },  _type == "wysiwyg" => {    body[]{      ...,      _type == "image" => {  ...,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,}    }  }},  seo{  metaTitle,  metaDescription,  noIndex,  ogImage {  ...,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,}},  settings{  theme,  showFooter,  footerPage->{ _type, "slug": slug.current }}}
export type HomeQueryResult = {
  _updatedAt: string;
  content: Array<
    | {
        _key: string;
        _type: "video";
        asset: {
          id: string;
          title: string | null;
          altText: string | null;
          storageKey: string | null;
          duration: number | null;
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
          poster: string | null;
          posterLqip: string | null;
        } | null;
        caption?: string;
        autoplay?: boolean;
        loop?: boolean;
        controls?: boolean;
      }
    | {
        _key: string;
        _type: "wysiwyg";
        body: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
              listItem?: "bullet";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              _type: "image";
              _key: string;
              width: number | null;
              height: number | null;
              lqip: string | null;
            }
        > | null;
      }
  > | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    noIndex: boolean | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      width: number | null;
      height: number | null;
      lqip: string | null;
    } | null;
  } | null;
  settings: {
    theme: "dark" | "light" | null;
    showFooter: boolean | null;
    footerPage: {
      _type: "home";
      slug: null;
    } | null;
  } | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "settings"][0]{  showPreloader,  nav[] {  label,  "external": linkType == "external",  "href": select(    linkType == "external" => url,    page->_type == "home" => "/",    null  )},  siteIdentity{    entityType,    name,    alternateName,    jobTitle,    email,    sameAs,    logo{      "url": asset->url,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height    }  },  aiContent{    summary,    sections[]{ title, items }  },  footer{    heading,    copyright,    links[] {  label,  "external": linkType == "external",  "href": select(    linkType == "external" => url,    page->_type == "home" => "/",    null  )},    socials[] {  label,  "external": linkType == "external",  "href": select(    linkType == "external" => url,    page->_type == "home" => "/",    null  )}  },  fallbackSEO{    metaTitle,    metaDescription,    ogImage {  ...,  "width": asset->metadata.dimensions.width,  "height": asset->metadata.dimensions.height,  "lqip": asset->metadata.lqip,}  }}
export type SiteSettingsQueryResult = {
  showPreloader: boolean | null;
  nav: Array<{
    label: string | null;
    external: false | true;
    href: string | "/" | null;
  }> | null;
  siteIdentity: {
    entityType: "organization" | "person" | null;
    name: string | null;
    alternateName: string | null;
    jobTitle: string | null;
    email: string | null;
    sameAs: Array<string> | null;
    logo: {
      url: string | null;
      width: number | null;
      height: number | null;
    } | null;
  } | null;
  aiContent: {
    summary: string | null;
    sections: Array<{
      title: string | null;
      items: Array<string> | null;
    }> | null;
  } | null;
  footer: {
    heading: string | null;
    copyright: string | null;
    links: Array<{
      label: string | null;
      external: false | true;
      href: string | "/" | null;
    }> | null;
    socials: Array<{
      label: string | null;
      external: false | true;
      href: string | "/" | null;
    }> | null;
  } | null;
  fallbackSEO: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      width: number | null;
      height: number | null;
      lqip: string | null;
    } | null;
  } | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: llmsQuery
// Query: {  "settings": *[_type == "settings"][0]{    siteIdentity{ entityType, name, jobTitle, email, sameAs },    aiContent{ summary, sections[]{ title, items } },    fallbackSEO{ metaTitle, metaDescription },    footer{ socials[] {  label,  "external": linkType == "external",  "href": select(    linkType == "external" => url,    page->_type == "home" => "/",    null  )} }  },  "home": *[_type == "home"][0] {  "type": _type,  _updatedAt,  seo{ metaTitle, metaDescription, noIndex },  content[]{  _type,  _type == "video" => { caption, "videoTitle": asset->title },  _type == "wysiwyg" => {    "blocks": body[_type == "block"]{ style, listItem, "text": pt::text(@) }  }}}}
export type LlmsQueryResult = {
  settings: {
    siteIdentity: {
      entityType: "organization" | "person" | null;
      name: string | null;
      jobTitle: string | null;
      email: string | null;
      sameAs: Array<string> | null;
    } | null;
    aiContent: {
      summary: string | null;
      sections: Array<{
        title: string | null;
        items: Array<string> | null;
      }> | null;
    } | null;
    fallbackSEO: {
      metaTitle: string | null;
      metaDescription: string | null;
    } | null;
    footer: {
      socials: Array<{
        label: string | null;
        external: false | true;
        href: string | "/" | null;
      }> | null;
    } | null;
  } | null;
  home: {
    type: "home";
    _updatedAt: string;
    seo: {
      metaTitle: string | null;
      metaDescription: string | null;
      noIndex: boolean | null;
    } | null;
    content: Array<
      | {
          _type: "video";
          caption: string | null;
          videoTitle: string | null;
        }
      | {
          _type: "wysiwyg";
          blocks: Array<{
            style: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal" | null;
            listItem: "bullet" | null;
            text: string;
          }> | null;
        }
    > | null;
  } | null;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "home"][0]{\n  _updatedAt,\n  content[]{\n  ...,\n  _type == "video" => {\n    asset-> {\n  "id": _id,\n  title,\n  altText,\n  storageKey,\n  duration,\n  width,\n  height,\n  aspectRatio,\n  "poster": thumbnail.asset->url,\n  "posterLqip": thumbnail.asset->metadata.lqip\n}\n  },\n  _type == "wysiwyg" => {\n    body[]{\n      ...,\n      _type == "image" => {\n  ...,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n}\n    }\n  }\n},\n  seo{\n  metaTitle,\n  metaDescription,\n  noIndex,\n  ogImage {\n  ...,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n}\n},\n  settings{\n  theme,\n  showFooter,\n  footerPage->{ _type, "slug": slug.current }\n}\n}': HomeQueryResult;
    '*[_type == "settings"][0]{\n  showPreloader,\n  nav[] {\n  label,\n  "external": linkType == "external",\n  "href": select(\n    linkType == "external" => url,\n    page->_type == "home" => "/",\n    null\n  )\n},\n  siteIdentity{\n    entityType,\n    name,\n    alternateName,\n    jobTitle,\n    email,\n    sameAs,\n    logo{\n      "url": asset->url,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height\n    }\n  },\n  aiContent{\n    summary,\n    sections[]{ title, items }\n  },\n  footer{\n    heading,\n    copyright,\n    links[] {\n  label,\n  "external": linkType == "external",\n  "href": select(\n    linkType == "external" => url,\n    page->_type == "home" => "/",\n    null\n  )\n},\n    socials[] {\n  label,\n  "external": linkType == "external",\n  "href": select(\n    linkType == "external" => url,\n    page->_type == "home" => "/",\n    null\n  )\n}\n  },\n  fallbackSEO{\n    metaTitle,\n    metaDescription,\n    ogImage {\n  ...,\n  "width": asset->metadata.dimensions.width,\n  "height": asset->metadata.dimensions.height,\n  "lqip": asset->metadata.lqip,\n}\n  }\n}': SiteSettingsQueryResult;
    '{\n  "settings": *[_type == "settings"][0]{\n    siteIdentity{ entityType, name, jobTitle, email, sameAs },\n    aiContent{ summary, sections[]{ title, items } },\n    fallbackSEO{ metaTitle, metaDescription },\n    footer{ socials[] {\n  label,\n  "external": linkType == "external",\n  "href": select(\n    linkType == "external" => url,\n    page->_type == "home" => "/",\n    null\n  )\n} }\n  },\n  "home": *[_type == "home"][0] {\n  "type": _type,\n  _updatedAt,\n  seo{ metaTitle, metaDescription, noIndex },\n  content[]{\n  _type,\n  _type == "video" => { caption, "videoTitle": asset->title },\n  _type == "wysiwyg" => {\n    "blocks": body[_type == "block"]{ style, listItem, "text": pt::text(@) }\n  }\n}\n}\n}': LlmsQueryResult;
  }
}
